In [1]:
import numpy as np

In [2]:
A = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [3]:
print A.shape

(2, 2, 2)


In [4]:
B = np.array([[5],[6]])

In [5]:
print B.shape

(2, 1)


In [6]:
C = np.matmul(A,B)

In [7]:
print C.shape

(2, 2, 1)


In [8]:
print C

[[[17]
  [39]]

 [[17]
  [39]]]


In [9]:
print B

[[5]
 [6]]


In [10]:
print A

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [11]:
import tensorflow as tf

In [49]:
A = np.float32(A)
B = np.float32(B)
print A
print B
C = tf.tensordot(A,B, axes=1)

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 1.  2.]
  [ 3.  4.]]]
[[ 5.]
 [ 6.]]


In [50]:
with tf.Session() as sess:
    print C.eval() 

[[[ 17.]
  [ 39.]]

 [[ 17.]
  [ 39.]]]
