In [1]:
import numpy as np

In [2]:
layer_rep = np.random.rand(1,38,5,5)

In [3]:
print layer_rep.shape

(1, 38, 5, 5)


In [4]:
print layer_rep

[[[[  5.93612950e-01   3.88200209e-01   8.43675831e-01   1.03242192e-01
      3.56732588e-01]
   [  7.18387311e-01   8.99497626e-01   1.13510149e-01   8.52181843e-01
      1.00580789e-01]
   [  4.76583950e-01   4.36565453e-02   7.20946533e-01   3.22480238e-01
      4.62425611e-01]
   [  6.07851374e-01   9.23076333e-01   6.63638594e-02   2.67564136e-01
      3.52091536e-01]
   [  2.03161969e-01   1.43395077e-01   3.87804111e-01   5.78237238e-01
      1.20080190e-01]]

  [[  2.44996589e-01   4.13649317e-01   2.68847938e-01   2.98500047e-01
      6.83209493e-01]
   [  8.47205212e-01   3.53313182e-01   9.51771700e-01   4.61086624e-01
      2.20488914e-01]
   [  7.10977139e-01   9.27021645e-02   3.98072361e-01   8.69787070e-01
      7.27586786e-01]
   [  9.22900096e-01   4.98628501e-01   7.32763991e-01   4.04436078e-01
      5.47409944e-01]
   [  4.85667375e-01   3.55421150e-01   7.03446462e-01   4.61809483e-01
      3.84312282e-01]]

  [[  7.27510344e-01   5.55349943e-01   4.98418001e-01  

In [5]:
itera = np.random.rand(2,35)

In [6]:
layer_rep[0,0]

array([[ 0.59361295,  0.38820021,  0.84367583,  0.10324219,  0.35673259],
       [ 0.71838731,  0.89949763,  0.11351015,  0.85218184,  0.10058079],
       [ 0.47658395,  0.04365655,  0.72094653,  0.32248024,  0.46242561],
       [ 0.60785137,  0.92307633,  0.06636386,  0.26756414,  0.35209154],
       [ 0.20316197,  0.14339508,  0.38780411,  0.57823724,  0.12008019]])

In [7]:
layer_rep[0,0,0]

array([ 0.59361295,  0.38820021,  0.84367583,  0.10324219,  0.35673259])

In [8]:
layer_rep[0,37,0]

array([ 0.97587697,  0.91135009,  0.28634496,  0.92644751,  0.24324036])

In [9]:
test_size = np.random.rand(1,3,5,5)

In [10]:
print test_size

[[[[ 0.93243642  0.72960199  0.33066878  0.18711012  0.5743574 ]
   [ 0.31085526  0.39073684  0.85747958  0.88956866  0.93377758]
   [ 0.59527643  0.55337053  0.90327574  0.06102535  0.46877814]
   [ 0.73092402  0.54926341  0.51212888  0.32316301  0.39048459]
   [ 0.0778846   0.14564554  0.27974303  0.0826138   0.85577835]]

  [[ 0.98155116  0.89515168  0.64074953  0.77126077  0.51796911]
   [ 0.05540004  0.84049694  0.36444824  0.76844352  0.34376093]
   [ 0.56393599  0.07449146  0.64191226  0.90877624  0.1244802 ]
   [ 0.57089813  0.1555218   0.95768769  0.4557743   0.54940925]
   [ 0.32960025  0.36354486  0.66938839  0.95805023  0.72293776]]

  [[ 0.27641855  0.73570438  0.45149201  0.82197546  0.16072141]
   [ 0.41422459  0.94748738  0.05850206  0.27171834  0.0545514 ]
   [ 0.95944369  0.3725327   0.6713487   0.49526636  0.88843464]
   [ 0.70286262  0.37984407  0.57080112  0.47903355  0.31812789]
   [ 0.82323164  0.37966425  0.25585668  0.03176394  0.58303047]]]]


In [11]:
egoism = np.array([0,0,0,1,0,0,0,0,1,0,0,0,0,0,1])

In [12]:
egoism = np.reshape(egoism, (1,3,5))

In [13]:
print egoism

[[[0 0 0 1 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]]


In [14]:
val = np.dot(egoism, test_size)
print val

[[[[[ 0.73092402  0.54926341  0.51212888  0.32316301  0.39048459]
    [ 0.57089813  0.1555218   0.95768769  0.4557743   0.54940925]
    [ 0.70286262  0.37984407  0.57080112  0.47903355  0.31812789]]]


  [[[ 0.73092402  0.54926341  0.51212888  0.32316301  0.39048459]
    [ 0.57089813  0.1555218   0.95768769  0.4557743   0.54940925]
    [ 0.70286262  0.37984407  0.57080112  0.47903355  0.31812789]]]


  [[[ 0.0778846   0.14564554  0.27974303  0.0826138   0.85577835]
    [ 0.32960025  0.36354486  0.66938839  0.95805023  0.72293776]
    [ 0.82323164  0.37966425  0.25585668  0.03176394  0.58303047]]]]]


In [15]:
val2 = np.matmul(egoism, test_size)

In [16]:
print val2

[[[[ 0.73092402  0.54926341  0.51212888  0.32316301  0.39048459]
   [ 0.73092402  0.54926341  0.51212888  0.32316301  0.39048459]
   [ 0.0778846   0.14564554  0.27974303  0.0826138   0.85577835]]

  [[ 0.57089813  0.1555218   0.95768769  0.4557743   0.54940925]
   [ 0.57089813  0.1555218   0.95768769  0.4557743   0.54940925]
   [ 0.32960025  0.36354486  0.66938839  0.95805023  0.72293776]]

  [[ 0.70286262  0.37984407  0.57080112  0.47903355  0.31812789]
   [ 0.70286262  0.37984407  0.57080112  0.47903355  0.31812789]
   [ 0.82323164  0.37966425  0.25585668  0.03176394  0.58303047]]]]


In [17]:
val3 = np.tensordot(egoism, test_size, ([2,1],[2,1]))

In [18]:
print val3.shape

(1, 1, 5)


In [19]:
print val3

[[[ 2.12505379  1.08444946  1.72567325  0.81070125  1.52292431]]]


In [20]:
egoism = np.reshape(egoism, (3,5))

In [21]:
test_size = np.reshape(test_size, (3,5,5))

In [22]:
print egoism

[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [23]:
print test_size

[[[ 0.93243642  0.72960199  0.33066878  0.18711012  0.5743574 ]
  [ 0.31085526  0.39073684  0.85747958  0.88956866  0.93377758]
  [ 0.59527643  0.55337053  0.90327574  0.06102535  0.46877814]
  [ 0.73092402  0.54926341  0.51212888  0.32316301  0.39048459]
  [ 0.0778846   0.14564554  0.27974303  0.0826138   0.85577835]]

 [[ 0.98155116  0.89515168  0.64074953  0.77126077  0.51796911]
  [ 0.05540004  0.84049694  0.36444824  0.76844352  0.34376093]
  [ 0.56393599  0.07449146  0.64191226  0.90877624  0.1244802 ]
  [ 0.57089813  0.1555218   0.95768769  0.4557743   0.54940925]
  [ 0.32960025  0.36354486  0.66938839  0.95805023  0.72293776]]

 [[ 0.27641855  0.73570438  0.45149201  0.82197546  0.16072141]
  [ 0.41422459  0.94748738  0.05850206  0.27171834  0.0545514 ]
  [ 0.95944369  0.3725327   0.6713487   0.49526636  0.88843464]
  [ 0.70286262  0.37984407  0.57080112  0.47903355  0.31812789]
  [ 0.82323164  0.37966425  0.25585668  0.03176394  0.58303047]]]


In [24]:
print egoism.T.shape

(5, 3)


In [25]:
val4 = np.tensordot(egoism, test_size, (1,2))

In [26]:
print val4[0].shape

(3, 5)


In [27]:
np.argmax(egoism, 0)

array([0, 0, 0, 0, 2])

In [28]:
print val4[0]

[[ 0.18711012  0.88956866  0.06102535  0.32316301  0.0826138 ]
 [ 0.77126077  0.76844352  0.90877624  0.4557743   0.95805023]
 [ 0.82197546  0.27171834  0.49526636  0.47903355  0.03176394]]


In [29]:
np.array(val4[0],dtype='int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [30]:
ego_size = np.array([[1,2,3,4,5]])

In [31]:
print ego_size.shape

(1, 5)


In [32]:
ego_size[0]

array([1, 2, 3, 4, 5])

In [33]:
ego_size[0,1]

2

In [34]:
ego_size.shape[0] - 3

-2

In [35]:
import keras.layers as layers

Using TensorFlow backend.


In [36]:
import keras.backend as K

In [37]:
eggo = K.variable(ego_size)

In [38]:
int(eggo[0].shape[0])

5

In [39]:
eggo[0,0].shape

TensorShape([])

In [40]:
eggo

<tf.Variable 'Variable:0' shape=(1, 5) dtype=float32_ref>

In [41]:
val_batch = np.array([[3]])

In [42]:
print val_batch, val_batch.shape

[[3]] (1, 1)


In [43]:
val_batch = K.variable(val_batch)

In [44]:
print val_batch, val_batch.shape

<tf.Variable 'Variable_1:0' shape=(1, 1) dtype=float32_ref> (1, 1)


In [49]:
val_batch[0].shape

TensorShape([Dimension(1)])